import argparse
import csv
import glob
import json
import logging
import os
import re
import statistics
import sys
from typing import Tuple

import tqdm


class LIS:
  def __init__(self, name: str,
      chain_i: str, chain_j: str,
      ilis: float, lis: float, lia: float,
      iptm: float, ptm: float):
    self.name = name
    self.chain_i = chain_i
    self.chain_j = chain_j
    self.ilis = ilis
    self.lis = lis
    self.lia = lia
    self.iptm = iptm
    self.ptm = ptm


def readable_file(filepath: str):
  """Checks if a file exists and is readable, or if it's "-" for stdin."""
  if filepath == "-":
    return filepath  # Special case for stdin/stdout path name

  if not os.path.exists(filepath):
    # Raise ArgumentTypeError to make argparse show a clean error message
    raise argparse.ArgumentTypeError(f"File not found: {filepath}")

  if not os.access(filepath, os.R_OK):
    raise argparse.ArgumentTypeError(f"File not readable: {filepath}")

  # If all checks pass, return the original string (the filepath)
  return filepath


def writable_path(filepath: str):
  """Checks if the path is potentially writable, or if it's '-' for stdout."""
  if filepath == "-":
    return filepath  # Special case for stdin/stdout path name

  # Check if directory exists (and create it if you want, but simple check is enough)
  # A simple check for writability can be complex, so for most CLI tools,
  # just returning the string is fine, and let 'open()' handle the creation/error.
  # We'll just return the string for simplicity here.
  return filepath


def dir_path(string: str):
  if not string or os.path.isdir(string):
    return string
  else:
    raise NotADirectoryError(string)


logger = logging.getLogger("af3lis")
METRICS = ["iptm", "ptm", "lis"]


def main(argv: list[str] = None):
  logging.basicConfig(filename='af3lis.log', level=logging.DEBUG,
                      format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

  parser = argparse.ArgumentParser(
    description="Extract ipTM score (or other) from summary confidence JSON files generated by AlphaFold 3.")
  parser.add_argument("-i", "--input", type=dir_path, default="",
                      help="Base directory to look for summary confidence JSON files  (default: current directory)")
  parser.add_argument("-o", "--output", type=writable_path, default="-",
                      help="Tab delimited output file containing scores  (default: standard output '-')")
  parser.add_argument("-m", "--metrics", nargs="+", choices=METRICS,
                      default=[METRICS[0]],
                      help="Metrics to output  (default: %(default)s)")
  parser.add_argument("-n", "--name",
                      default=r"([\w-]+)__([\w-]+)_summary_confidences",
                      help="Regular expression to obtain bait/target names based on confidence filename "
                           " (default: %(default)s)")
  parser.add_argument("-1", "--sequence1", type=int, default=1,
                      help="Index of sequence one in the *_data.json file (default: %(default)s)")
  parser.add_argument("-2", "--sequence2", type=int, default=2,
                      help="Index of sequence two in the *_data.json file (default: %(default)s)")
  parser.add_argument("-l", "--lis", type=readable_file,
                      default="structures/structures_lis_analysis.csv",
                      help="File containing LIS scores - created by lis.py")
  parser.add_argument("-p", "--progress", action="store_true", default=False,
                      help="Show progress bar")
  parser.add_argument("-M", "--mapping", type=readable_file,
                      help="Tab delimited text file used to convert names")
  parser.add_argument("-S", "--source_column", type=int, default="1",
                      help="Column index of source names in mapping file - 1 means first column of file" +
                           "   (default: %(default)s)")
  parser.add_argument("-C", "--converted_column", type=int, default="2",
                      help="Column index of converted names in mapping file - 1 means first column of file" +
                           "   (default: %(default)s)")

  args = parser.parse_args(argv)

  af3_score(input_dir=args.input, output_file=args.output,
            name=args.name,
            metrics=args.metrics,
            sequence_one=args.sequence1 - 1,
            sequence_two=args.sequence2 - 1,
            lis_file=args.lis,
            progress=args.progress,
            mapping_file=args.mapping,
            source_column=args.source_column - 1,
            converted_column=args.converted_column - 1)


def af3_score(input_dir: str = "",
    output_file: str = "-", name: str = r"([\w-]+)__([\w-]+)",
    metrics: list[str] = None,
    sequence_one: int = 0, sequence_two: int = 1,
    lis_file: str = "structures/structures_lis_analysis.csv",
    progress: bool = False,
    mapping_file: str = None, source_column: int = 0,
    converted_column: int = 1):
  """
  Extract ipTM score (or other) from summary confidence JSON files generated by AlphaFold 3.

  :param input_dir: input directory
  :param output_file: output file
  :param name: regular expression to obtain protein/gene names based on confidence filename
  :param metrics: metrics to output
  :param sequence_one: index of sequence one in the *_data.json file
  :param sequence_two: index of sequence two in the *_data.json file
  :param lis_file: file containing LIS scores - created by lis.py
  :param progress: if True, show progress bar
  :param mapping_file: tab delimited text file used to convert names
  :param source_column: column index of source names in mapping file
  :param converted_column: column index of converted names in mapping file
  """
  if metrics is None:
    metrics = [METRICS[0]]
  if len(metrics) == 0:
    raise AssertionError("metrics must have at least one value")
  if len([metric for metric in metrics if metric not in METRICS]) > 0:
    raise AssertionError(
      f"metrics values must all be present in {METRICS}")
  if not lis_file:
    raise AssertionError("lis_file parameter is required")

  # Find AlphaFold 3 confidence files.
  confidence_files = sorted(
    glob.glob("**/*_summary_confidences.json", root_dir=input_dir,
              recursive=True))
  seed_pattern = re.compile(r"seed-\d+_sample-\d+")
  confidence_files = [confidence_file for confidence_file in confidence_files if
                      not seed_pattern.search(confidence_file)]
  confidence_files = [os.path.join(input_dir, confidence_file) for
                      confidence_file in confidence_files]

  # Parse mapping.
  mappings = {}
  if mapping_file:
    mappings = parse_mapping(mapping_file, source_column, converted_column)

  # Parse LIS files.
  all_lis = parse_lis(lis_file)

  # Get scores.
  all_scores = []
  for confidence_file in tqdm.tqdm(
      confidence_files) if progress else confidence_files:
    all_scores.append(
      get_confidence_scores(confidence_file, metrics, all_lis, sequence_one,
                            sequence_two))

  # Write to output
  with open(output_file,
            "w") if output_file != "-" else sys.stdout as output_file_out:
    output_file_out.write("Bait\tTarget")
    for metric in metrics:
      if "iptm" == metric:
        output_file_out.write("\tipTM")
      elif "ptm" == metric:
        output_file_out.write("\tpTM")
      elif "ranking_score" == metric:
        output_file_out.write("\tRanking score")
      elif "lis" == metric:
        output_file_out.write("\tiLIS\tLIS\tLIA")
    output_file_out.write("\n")
    for confidence_file, scores in all_scores:
      re_match = re.search(name, confidence_file)
      if not re_match:
        raise AssertionError(
          f"Expression {name} cannot be found in filename {confidence_file}")
      bait, target = re_match.group(1, 2)
      bait = mappings[bait] if bait in mappings else bait
      target = mappings[target] if target in mappings else target
      output_file_out.write(f"{bait}\t{target}")
      for score in scores:
        output_file_out.write(f"\t{score}")
      output_file_out.write("\n")


def get_confidence_scores(confidence_file: str, metrics: list[str] = None,
    all_lis: list[LIS] = None,
    sequence_one: int = 0, sequence_two: int = 1) -> Tuple[str, list[float]]:
  """
  Returns confidence scores for given metrics

  :param confidence_file: confidence JSON file
  :param metrics: metrics to obtain confidence scores
  :param all_lis: LIS objects
  :param sequence_one: index of sequence one
  :param sequence_two: index of sequence two
  :return: list of confidence scores for the different metrics
  """
  if metrics is None:
    metrics = [METRICS[0]]
  if len([metric for metric in metrics if metric not in METRICS]) > 0:
    raise AssertionError(
      f"metrics values must all be present in {METRICS}")
  if all_lis is None:
    raise AssertionError("all_lis parameter is required")

  sequence_one_id, sequence_two_id = get_sequence_ids(confidence_file,
                                                      sequence_one,
                                                      sequence_two)
  lis_name = os.path.basename(confidence_file).replace(
    "_summary_confidences.json", "")
  confidences = [lis for lis in all_lis if
                 lis.name == lis_name and (
                     (
                         lis.chain_i == sequence_one_id and lis.chain_j == sequence_two_id) or (
                         lis.chain_j == sequence_one_id and lis.chain_i == sequence_two_id))]

  scores = []
  for metric in metrics:
    if "iptm" == metric:
      scores.append(max([lis.iptm for lis in confidences]))
    elif "ptm" == metric:
      scores.append(max([lis.ptm for lis in confidences]))
    elif "lis" == metric:
      scores.append(statistics.mean([lis.ilis for lis in confidences]))
      scores.append(statistics.mean([lis.lis for lis in confidences]))
      scores.append(statistics.mean([lis.lia for lis in confidences]))
  return confidence_file, scores


def get_sequence_ids(confidence_file: str,
    sequence_one: int = 0, sequence_two: int = 1) -> Tuple[str, str]:
  """
  Returns id of sequence one and two from the *_data.json file.

  :param confidence_file: confidence JSON file
  :param sequence_one: index of sequence one in the *_data.json file
  :param sequence_two: index of sequence two in the *_data.json file
  :return: tuple containing (sequence_one_id, sequence_two_id)
  where sequence_one_id is the id of sequence one
  and sequence_one_id is the id of sequence two
  """
  data_json = confidence_file.replace("_summary_confidences.json",
                                      "_data.json")
  data = load_json(data_json)
  sequence_type = list(data["sequences"][sequence_one].keys())[0]
  sequence_one_id = data["sequences"][sequence_one][sequence_type]["id"]
  sequence_type = list(data["sequences"][sequence_two].keys())[0]
  sequence_two_id = data["sequences"][sequence_two][sequence_type]["id"]
  return sequence_one_id, sequence_two_id


def parse_lis(lis_file: str) \
    -> list[LIS]:
  """
  Parse file containing LIS scores.

  :param lis_file: file containing LIS scores - created by lis.py
  :return: dictionary of source id to converted id
  """
  all_lis = []
  with open(lis_file, "r") if lis_file != "-" else sys.stdin as lis_file_in:
    for row in csv.DictReader(lis_file_in):
      all_lis.append(
        LIS(name=row["name"], chain_i=row["chain_i"], chain_j=row["chain_j"],
            ilis=float(row["iLIS"]), lis=float(row["LIS"]),
            lia=float(row["LIA"]),
            iptm=float(row["ipTM"]), ptm=float(row["pTM"])))
  return all_lis


def parse_mapping(mapping_file: str, source_column: int = 0,
    converted_column: int = 1) \
    -> dict[str, str]:
  """
  Parse mapping file.

  :param mapping_file: text delimited filename
  :param source_column: index of source id columns
  :param converted_column: index of converted id columns
  :return: dictionary of source id to converted id
  """
  mappings = {}
  with open(mapping_file,
            "r") if mapping_file != "-" else sys.stdin as mapping_file_in:
    for line in mapping_file_in:
      if line.startswith("#"):
        continue
      columns = line.rstrip("\r\n").split("\t")
      source = columns[source_column].lower()
      converted = columns[converted_column]
      if converted:
        mappings[source] = converted
  return mappings


def load_json(file) -> dict:
  with open(file, "r") as file_in:
    try:
      return json.load(file_in)
    except json.decoder.JSONDecodeError as e:
      logger.error(f"Error loading JSON file {file}")
      raise e


if __name__ == "__main__":
  main()
